---
# tasks file for netconfigure

  - name: Generate config file netplan for labnode1 and labnode3
    template: src=netplanconfig.j2 dest={{destfile}}/netplanconfig.yaml mode=644
    when: ansible_hostname != 'labnode2'
    notify:
      - Netplan apply

  - name: Generate config file netplan for labnode2
    template: src=config2interface.j2 dest={{destfile}}/config2interface.yaml
    when: ansible_hostname == 'labnode2'
    notify:
      - Netplan apply

  - block:

      - name: config iptables to labnode3
        iptables:
          table: nat
          chain: POSTROUTING
          out_interface: eth2
          jump: SNAT
          to_source: "{{ipeth2}}"

      - name: config iptables to labnode1
        iptables:
          table: nat
          chain: POSTROUTING
          out_interface: eth1
          jump: SNAT
          to_source: "{{ipeth1}}"

      - name: Set ip forwarding
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes

    when: ansible_hostname == 'labnode2'
